### ISSUE TITLE
Rathleon doors, are not supported as house door.

### ISSUE THREAD

**Issue by mokerhamer** [ricker75/Remere-s-Map-Editor-10.80#1]
Like the title sais. 

It dosen't display discreption of house price. After taiking a closer looks. The door's lack of Door's id needed for houses.
http://puu.sh/iLPZj/3eb2ce841a.jpg   <-- Used a default door, worked fine.

http://puu.sh/iLQ1w/fe24cb2e64.jpg  <--- Bugging, i can open/close door but cant enter.

**Comment by ricker75** [comment]
probably be a problem of its global.lua
http://i.imgur.com/mmhYYL0.png <--- Closed door
http://i.imgur.com/Es21XZN.png   <---  Open Door

**Comment by mokerhamer** [comment]
I have already compared it with TFS and orts server, same.. going to track down whats the cause

**Comment by ricker75** [comment]
Orts and tfs Use different items.otb and those who use my remeres are old code version 1055 which I consider more stable... 

Now I work to take out a data pack with that version of items https://github.com/ricker75/Global-Server

But if you want I can update the items.otb ORTS or TFS version you need to work
