### ISSUE TITLE
Cannot find dat and spr file

### ISSUE THREAD

**Issue by Neomex000** [ricker75/Remere-s-Map-Editor-10.80#2]
Hello, I download tibia 10.91 and 10.9 and both dont work with the editor. I'm setting the paths in preferences and when it asks me for it but it doesn't detect any files.
Please help.

11:56:43: Signatures are incorrect.
Dat signature: 3F81
Spr signature: 56BC8198
11:56:43: Signatures are incorrect.
Dat signature: 3F81
Spr signature: 56BC8198
11:56:48: Signatures are incorrect.
Dat signature: 3F81
Spr signature: 56BC8198

**Comment by ricker75** [comment]
assigned support to 10.91 in 3 days update items and more
